const $=id=>document.getElementById(id);
const API=window.POOL_API || 'https://pool-moment-lee-0929.xmnqpqzqpg11.chatgpt.site';
const faces=['🐱','🐼','🐰','🦊','🐶','🐨'];
const positions=[[12,14],[53,9],[32,29],[70,31],[9,47],[49,48],[25,68],[68,69],[7,76],[70,49],[33,9],[43,77]];
let state={me:null,pools:{boy:{count:null,members:[]},girl:{count:null,members:[]}}};
let token='',draft='🐱',pending=null,browsing=false,busy=false,refreshing=null,toastTimer,pollTimer,loaded=false,storageOK=true;
try{token=localStorage.getItem('pool-session-v1')||'';if(!/^[a-f0-9]{64}$/.test(token)){token=[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,'0')).join('');localStorage.setItem('pool-session-v1',token)}}catch{storageOK=false}
function notify(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000)}
function setStatus(text,failed=false){$('syncStatus').textContent=text;$('retrySync').hidden=!failed;$('profileError').textContent=failed?text:''}
function setBusy(value){busy=value;document.querySelectorAll('#profileForm button,#choices button,#boyJoin,#girlJoin,#edit,#closeProfile').forEach(b=>b.disabled=value);$('nickname').disabled=value}
async function api(path,method='GET',data){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(API+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{}),cache:'no-store',signal:controller.signal});let result;try{result=await response.json()}catch{throw Error('云服务连接失败，请重试')}if(!response.ok)throw Error(result.error||'请求失败，请重试');return result}catch(error){if(error.name==='AbortError')throw Error('连接超时，请重试');throw error}finally{clearTimeout(timeout)}}
function avatar(member,index){const mine=member.id===state.me?.id,b=document.createElement('button');b.className='avatar'+(mine?' mine':'');b.setAttribute('aria-label',member.name+(mine?'，我':''));b.style.left=positions[index][0]+'%';b.style.top=positions[index][1]+'%';b.style.animationDelay=-(index%5)+'s';const f=document.createElement('span');f.className='face';f.textContent=member.face;b.append(f);b.onclick=()=>{$('personFace').textContent=member.face;$('personName').textContent=member.name+(mine?' · 我':'');$('personPool').textContent=member.pool;$('person').showModal()};return b}
function render(animate=false){document.querySelector('main').hidden=!browsing&&!state.me;$('closeProfile').hidden=!state.me;for(const p of ['boy','girl']){const box=$(p+'Pool');box.replaceChildren();state.pools[p].members.forEach((member,i)=>{const a=avatar(member,i);if(animate&&member.id===state.me?.id){a.style.animationDelay='0s';a.classList.add('arrival');a.addEventListener('animationend',()=>a.classList.remove('arrival'),{once:true})}box.append(a)});$(p+'Count').textContent=state.pools[p].count??'—';$(p+'Join').classList.toggle('active',state.me?.pool===p);$(p+'Join').textContent=state.me?.pool===p?'✓ 我在这里':state.me?.pool?'切换到 '+p:'加入 '+p}$('myFace').textContent=state.me?.face||'🐱';$('myName').textContent=state.me?.name||'池边的新朋友'}
async function refresh(animate=false){if(refreshing)return refreshing;refreshing=(async()=>{try{state=await api('/api/pools');loaded=true;render(animate);setStatus('人数已同步 · 每 5 秒更新');return true}catch(error){setStatus(error.message||'同步失败，请重试',true);return false}finally{refreshing=null}})();return refreshing}
function chooseFace(face){draft=face;$('draftFace').textContent=face;[...$('choices').children].forEach(b=>{b.classList.toggle('selected',b.textContent===face);b.setAttribute('aria-pressed',String(b.textContent===face))})}
function openProfile(){if(busy)return;$('nickname').value=state.me?.name||'';$('nickname').setCustomValidity('');chooseFace(state.me?.face||'🐱');if(!$('profile').open)$('profile').showModal()}
function cancelProfile(){if(busy)return;pending=null;browsing=true;$('profile').close();render()}
async function join(pool){if(busy)return;if(!state.me){pending=pool;openProfile();return}if(state.me.pool===pool)return;setBusy(true);let committed=false;try{if(refreshing)await refreshing;await api('/api/join','POST',{pool});committed=true;const synced=await refresh(true);notify(synced?'已加入 '+pool:'加入已保存，人数同步稍后重试')}catch(error){notify(error.message||'加入失败，请重试')}finally{setBusy(false);if(committed)browsing=true}}
faces.forEach(face=>{const b=document.createElement('button');b.type='button';b.className='choice';b.textContent=face;b.setAttribute('aria-label','使用'+face+'头像');b.onclick=()=>chooseFace(face);$('choices').append(b)});
$('profileForm').onsubmit=async e=>{e.preventDefault();if(busy)return;const name=$('nickname').value.trim();if(!name){$('nickname').setCustomValidity('请输入微信昵称');$('nickname').reportValidity();return}if(!storageOK){$('profileError').textContent='浏览器无法保存身份，请允许网站存储后重试';return}setBusy(true);let saved=false;try{if(refreshing)await refreshing;await api('/api/profile','POST',{name,face:draft});saved=true;const synced=await refresh();if(synced){browsing=true;$('profile').close();render();notify('资料已保存')}else $('profileError').textContent='资料已保存，同步失败，请重试'}catch(error){$('profileError').textContent=error.message||'保存失败，请重试'}finally{setBusy(false)}if(saved&&!$('profile').open&&pending){const pool=pending;pending=null;await join(pool)}};
$('nickname').oninput=()=>$('nickname').setCustomValidity('');$('closeProfile').onclick=$('cancelProfile').onclick=cancelProfile;$('profile').addEventListener('cancel',e=>{e.preventDefault();cancelProfile()});$('edit').onclick=()=>{pending=null;openProfile()};$('boyJoin').onclick=()=>join('boy');$('girlJoin').onclick=()=>join('girl');$('closePerson').onclick=$('okay').onclick=()=>$('person').close();$('retrySync').onclick=()=>refresh();
function poll(){clearTimeout(pollTimer);pollTimer=setTimeout(async()=>{if(!document.hidden&&!busy)await refresh();poll()},5000)}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!busy)refresh()});window.addEventListener('online',()=>{if(!busy)refresh()});
(async()=>{setStatus('正在连接云端…');await refresh();if(!state.me)openProfile();else browsing=true;render();poll()})();
